from fpdf import FPDF
from .colors import PRIMARY

class InvoicePDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        self.set_fill_color(*PRIMARY)
        self.rect(0, 0, 210, 25, 'F')
        self.set_text_color(255, 255, 255)
        self.set_font("Arial", "B", 22)
        self.set_xy(10, 8)
        self.cell(0, 10, "PyBazar Ltd.", ln=True, align="L")
        self.set_font("Arial", "", 10)
        self.set_xy(10, 18)
        self.cell(0, 6, "123 Business Rd, Dhaka, Bangladesh", ln=True)
        self.set_xy(10, 24)
        self.cell(0, 6, "Email: support@pybazar.com | Phone: +880-123456789", ln=True)
        self.ln(10)
        self.set_y(32)
        self.set_text_color(*PRIMARY)
        self.set_font("Arial", "B", 15)
        self.cell(0, 12, "INVOICE / PAYMENT RECEIPT", ln=True, align="C")
        self.ln(2)
        self.set_draw_color(*PRIMARY)
        self.set_line_width(1)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)
        self.set_line_width(0.3)

    def footer(self):
        self.set_y(-30)
        self.set_font("Arial", "I", 8)
        self.set_text_color(*PRIMARY)
        self.multi_cell(0, 5, "This invoice confirms receipt of your payment.\nThank you for choosing PyBazar!\nGenerated by BillCraft © 2025", align='C')
